# Generated by Django 6.0.3 on 2026-03-15 16:14

import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Категория')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Категория денежного потока',
                'verbose_name_plural': 'Категории денежных потоков',
                'db_table': 'cashflow_category',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название валюты', max_length=50, verbose_name='Название')),
                ('code', models.CharField(help_text='Трехбуквенный код валюты', max_length=3, unique=True, verbose_name='Код валюты')),
                ('symbol', models.CharField(help_text='Символ валюты ($, €, ₽ и т.д.)', max_length=5, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='status')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Статус денежного потока',
                'verbose_name_plural': 'Статусы денежных потоков',
                'db_table': 'cashflow_status',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='type')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Тип денежного потока',
                'verbose_name_plural': 'Типы денежных потоков',
                'db_table': 'cashflow_type',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Подкатегория')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='finance.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория денежного потока',
                'verbose_name_plural': 'Подкатегории денежных потоков',
                'db_table': 'cashflow_subcategory',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.type', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Категория')),
                ('currency', models.ForeignKey(default=finance.models.get_currency, on_delete=django.db.models.deletion.PROTECT, to='finance.currency', verbose_name='Валюта')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.status', verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Денежный поток',
                'verbose_name_plural': 'Денежные потоки',
                'db_table': 'cashflow',
            },
        ),
    ]
