# Generated by Django 6.0.3 on 2026-03-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date_created',
            field=models.DateField(blank=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='time_created',
            field=models.DateTimeField(blank=True, verbose_name='Время создания'),
        ),
    ]
