# Generated by Django 6.0.3 on 2026-03-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_cashflow_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='time_created',
        ),
    ]
