# Generated by Django 6.0.3 on 2026-03-15 16:34

from django.db import migrations
from django.core.management import call_command
import os

def load_fixture(apps, schema_editor):
    # Проверяем, есть ли уже данные
    Status = apps.get_model('finance', 'Status')
    Type = apps.get_model('finance', 'Type')
    Currency = apps.get_model('finance', 'Currency')
    Category = apps.get_model('finance', 'Category')
    Subcategory = apps.get_model('finance', 'Subcategory')
    if True not in [Status.objects.exists(), Type.objects.exists(), Currency.objects.exists(), Category.objects.exists(), Subcategory.objects.exists()]:
        fixture_file = os.path.join(os.path.dirname(__file__), '../fixtures/data.json')
        call_command('loaddata', fixture_file, app_label='finance')


def reverse_load_fixture(apps, schema_editor):
    """Отмена загрузки"""
    Status = apps.get_model('finance', 'Status')
    Type = apps.get_model('finance', 'Type')
    Currency = apps.get_model('finance', 'Currency')
    Category = apps.get_model('finance', 'Category')
    Subcategory = apps.get_model('finance', 'Subcategory')

    # Очищаем таблицы в правильном порядке (учитывая внешние ключи)
    Subcategory.objects.all().delete()
    Category.objects.all().delete()
    Status.objects.all().delete()
    Type.objects.all().delete()
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_cashflow_time_created'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_load_fixture),
    ]
