# Generated by Django 6.0.3 on 2026-03-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_load_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='finance.subcategory', verbose_name='Подкатегория'),
        ),
    ]
