# Generated by Django 6.0.3 on 2026-03-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cashflow_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='finance.type', verbose_name='Тип'),
        ),
    ]
