server {
    listen 8088; # слушает внутренний порт из докера
    server_name localhost;

    # Docker-style logging
    access_log /dev/stdout;
    error_log  /dev/stderr warn;

    location / {
        proxy_pass http://cashflow-server:8000;
        include proxy_headers.conf; # Подключаем файл с заголовками

        proxy_connect_timeout 60s;  # Таймаут на установку соединения с бэкендом.
        proxy_read_timeout 60s;  # Таймаут на чтение ответа от бэкенда.
    }

    # Отключаем логирование для favicon.ico
    location /favicon.ico {
        access_log off;
        log_not_found off;
    }

    # Загружаем статику из docker и раздаем по адресу static
    location /static/ {
        alias /app/www/cashflow/staticfiles/;
    }
}