# Общие прокси-настройки
proxy_set_header X-Real-IP $remote_addr; # Передаёт оригинальный IP-адрес клиента.
proxy_set_header X-Forwarded-Proto $scheme; # Указывает исходный протокол (HTTP/HTTPS).
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Передаёт реальный IP-адрес клиента.
proxy_set_header Host $host; # Сохраняет оригинальный заголовок Host из запроса клиента. $host - всегда без порта (example.com)
proxy_set_header X-Forwarded-Host $server_name; # Передаёт имя сервера, которое обработало запрос.
proxy_redirect off; # Запрещает Nginx изменять URL в редиректах от Gunicorn
proxy_set_header X-Forwarded-Port 443;